/**
 * Generate a helpConfig skeleton from id hits discovered in source markup (the reverse of audit.js).
 * Pure: it takes the hits from scanSourceIds() and returns a string — the CLI decides whether to print
 * it or write it to a file. Aimed at the first step of adopting HelpLayer on an existing app: emit one
 * stub entry per data-help-id so you only have to fill in the wording.
 */

// A bare object key is only safe unquoted when it's a valid JS identifier; quote anything else.
function isSafeKey(key) {
  return /^[A-Za-z_$][\w$]*$/.test(key);
}

/** Escape a string for a single-quoted JS literal (matches the project's quote style). */
function escapeJsString(value) {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/'/g, '\\\'')
    .replace(/\r/g, '')
    .replace(/\n/g, '\\n');
}

/**
 * Collapse hits to one entry per id (first occurrence wins for location; inline title/text values are
 * picked up from whichever occurrence carries them), dropping ids already present in the config.
 * @param {import('./audit.js').IdHit[]} hits
 * @param {Set<string>} existingKeys
 */
function dedupeEntries(hits, existingKeys) {
  /** @type {Map<string, { id: string, file: string, line: number, title: string|null, text: string|null }>} */
  const seen = new Map();
  for (const hit of hits) {
    if (existingKeys.has(hit.id)) {
      continue;
    }
    const existing = seen.get(hit.id);
    if (existing) {
      // Backfill inline values from a later occurrence if the first one lacked them.
      existing.title = existing.title ?? hit.titleValue;
      existing.text = existing.text ?? hit.textValue;
      continue;
    }
    seen.set(hit.id, { id: hit.id, file: hit.file, line: hit.line, title: hit.titleValue, text: hit.textValue });
  }
  return [...seen.values()].sort((a, b) => a.id.localeCompare(b.id));
}

function renderJs(entries) {
  const lines = ['// Generated by `help-layer scaffold`. Fill in title/text for each entry.', 'export const helpConfig = {'];
  for (const entry of entries) {
    const key = isSafeKey(entry.id) ? entry.id : `'${escapeJsString(entry.id)}'`;
    const title = `'${escapeJsString(entry.title ?? '')}'`;
    const text = `'${escapeJsString(entry.text ?? '')}'`;
    lines.push(`  ${key}: { title: ${title}, text: ${text} }, // ${entry.file}:${entry.line}`);
  }
  lines.push('};');
  return lines.join('\n');
}

function renderJson(entries) {
  /** @type {Record<string, { title: string, text: string }>} */
  const obj = {};
  for (const entry of entries) {
    obj[entry.id] = { title: entry.title ?? '', text: entry.text ?? '' };
  }
  return JSON.stringify(obj, null, 2);
}

/**
 * Build the scaffold output string.
 * @param {object} params
 * @param {import('./audit.js').IdHit[]} params.hits from scanSourceIds()
 * @param {Set<string>} [params.existingKeys] config keys to skip (already defined)
 * @param {'js'|'json'} [params.format]
 * @returns {{ content: string, count: number }} content to emit and how many stub entries it holds
 */
export function buildScaffold({ hits, existingKeys = new Set(), format = 'js' }) {
  const entries = dedupeEntries(hits, existingKeys);
  const content = format === 'json' ? renderJson(entries) : renderJs(entries);
  return { content, count: entries.length };
}
